# Generated by Django 4.2.5 on 2023-09-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rarity',
            field=models.TextField(default='uncommon', editable=False),
        ),
    ]
